# Generated by Django 5.1 on 2024-08-24 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SemioticSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposition_1', models.CharField(max_length=255)),
                ('opposition_2', models.CharField(max_length=255)),
                ('neutral_term', models.CharField(blank=True, max_length=255, null=True)),
                ('contradictory_term', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semiotic_squares', to='api.text')),
            ],
        ),
    ]
