# Generated by Django 5.1 on 2024-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semioticsquare',
            name='contradictory_term',
        ),
        migrations.RemoveField(
            model_name='semioticsquare',
            name='opposition_1',
        ),
        migrations.RemoveField(
            model_name='semioticsquare',
            name='opposition_2',
        ),
        migrations.RemoveField(
            model_name='semioticsquare',
            name='text',
        ),
        migrations.AddField(
            model_name='semioticsquare',
            name='opposition1_term1',
            field=models.CharField(default='text', max_length=255),
        ),
        migrations.AddField(
            model_name='semioticsquare',
            name='opposition1_term2',
            field=models.CharField(default='text', max_length=255),
        ),
        migrations.AddField(
            model_name='semioticsquare',
            name='opposition2_term1',
            field=models.CharField(default='text', max_length=255),
        ),
        migrations.AddField(
            model_name='semioticsquare',
            name='opposition2_term2',
            field=models.CharField(default='text', max_length=255),
        ),
        migrations.AlterField(
            model_name='semioticsquare',
            name='neutral_term',
            field=models.CharField(default='text', max_length=255),
        ),
    ]
